spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: false
      exclude: WEB-INF/**
  servlet:
    multipart:
      max-file-size: 10Mb 
      max-request-size: 10Mb
wechat:
  appid: wxdbe78f60a273e8ea
  appsecret: 26260221b2770adfa7c261b1ea8de4c4
  signURL: http://152.136.41.165/checkSignature
  tokenKey: MyWeChatApp
  domain: http://152.136.41.165/